main: com.kill3rtaco.war.TacoWar
name: TacoWar
version: 1.0.0
depend: [TacoAPI]
commands:
  war:
    description: General Game commands
    aliases: [tacowar, tw, v]
  map:
    description: Map creation commands
    aliases: [twmap, twm, m]
  gametype:
    description: GameType creation commands
    aliases: [twgametype, twgt, gt]
  weapon:
    description: Weapon creation commands
    aliases: [twweapon, tww, w]
  kit:
    description: Kit creation commands
    aliases: [twkit, twk, k]
  playlist:
    description: Playist creation commands
    aliases: [twplaylist, twpl, pl, p]