name: TacoWar
main: com.kill3rtaco.war.TacoWar
version: 1.0
depend: [TacoAPI, WorldEdit]
commands:
  tacowar:
    description: Commands for TacoWar
    aliases: [tw, twar]
  twmap:
    description: TacoWar MapCreation commands
    aliases: [twm, tm, tmap]